# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eeef792170b270b5215fc9c604c7e329b8eb43ae5ceab53151eec13cb93d1706c509dde851b2c47bf3fd5a64d221392bc7a60969a556208469a79e5276d52c3

test:
  secret_key_base: 470c9f3132425b96051fbc56f3f9164245c617e94b6735e8ba0a7205cde298741854b78093c8179d6c7395d899560553ee31a711128bce6cf46622edd23f2a0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
